=== PhilippMundhenk/IVNS/ECUSimulation/config/timingSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.tum-create.edu.sg/timingSchema" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.tum-create.edu.sg/timingSchema">





    <complexType name="Timing">
    	<sequence>
    		<element name="timingMappings" type="tns:TimingMappings" minOccurs="1" maxOccurs="1"></element>
    		<element name="dbLookups" type="tns:DBLookups" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="TimingMappings">
    	<sequence>
    		<element name="timingMapping" type="tns:TimingMapping" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    


    <complexType name="DBLookups">
    	<sequence>
    		<element name="dbLookup" type="tns:DBLookup" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="TimingMapping">
    	<sequence>
    		<element name="dbLookupSpecs" type="tns:DBLookupSpecs" minOccurs="1" maxOccurs="1"></element>
    		<element name="dbInterpolSpecs"
    			type="tns:DBInterpolSpecs" minOccurs="1" maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="class" type="string"></attribute>
    </complexType>


    <complexType name="DBLookupSpecs">
    	<sequence>
    		<element name="dbLookupSpec" type="tns:DBLookupSpec" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="DBLookupSpec">
    	<sequence>
    		<element name="variable" type="tns:Variable" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="dbpath" type="string" use="required"></attribute>
    	<attribute name="lookupid" type="string" use="required"></attribute>
    </complexType>

    <complexType name="DBInterpolSpecs">
    	<sequence>
    		<element name="dbInterpolationSpec"
    			type="tns:DBInterpolSpec" minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="DBInterpolSpec">
    	<sequence>
    		<element name="variable" type="tns:Variable" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="dbpath" type="string" use="required"></attribute>
    	<attribute name="interpolmethod" type="string" use="required"></attribute>
    	<attribute name="lookupid" type="string" use="required"></attribute>
    </complexType>

    <complexType name="Variable">
    	<choice>
    		<element name="value" type="string"></element>
    	</choice>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="type" type="string" use="required"></attribute>
    	<attribute name="config" type="string" use="required"></attribute>
    </complexType>

    <complexType name="DBLookup">
    	<sequence>
    		<element name="dbLookupDesc" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="dbLookupRequest"
    			type="string" minOccurs="1" maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="id" type="int"></attribute>
    </complexType>















    <element name="timing" type="tns:Timing"></element>



    <element name="timingMappings" type="tns:TimingMappings"></element>
    
    <element name="timingMapping" type="tns:TimingMapping"></element>

    <element name="dbLookupSpec" type="tns:DBLookupSpec"></element>

    <element name="dbInterpolSpec" type="tns:DBInterpolSpec"></element>

    <element name="dbInterpolSpecs" type="tns:DBInterpolSpecs"></element>

    <element name="dbLookup" type="tns:DBLookup"></element>

    <element name="dbLookupDesc" type="string"></element>

    <element name="dbLookupRequest" type="string"></element>

    <element name="dbLookups" type="tns:DBLookups"></element>

    <element name="dbLookupSpecs" type="tns:DBLookupSpecs"></element>

    <element name="variable" type="tns:Variable"></element>




</schema>

=== PhilippMundhenk/IVNS/ECUSimulation/config/data/timingMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:timing xmlns:tns="http://www.tum-create.edu.sg/timingSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tum-create.edu.sg/timingSchema ../timingSchema.xsd ">
  
  <tns:timingMappings>
  	<tns:timingMapping name="STDTL_SEND_PROCESS" class="StdTransportLayer">
  		<tns:dbLookupSpecs>
  			<tns:dbLookupSpec dbpath="measurements.db" lookupid="1" id="DBLookup_1">
  				<tns:variable name="STDAL_SYM_CERTIFICATE_ALGORITHM" config="PROJECT" type="SymAuthMechEnum">
  					<tns:value>AES</tns:value>
  				</tns:variable>
  				<tns:variable name="SSCM_ECU_REG_MSG_SIZE" config="PROJECT" type="number">
  					<tns:value>20</tns:value>
  				</tns:variable>
  			</tns:dbLookupSpec>
  			<tns:dbLookupSpec dbpath="measurements.db" lookupid="2" id="DBLookup_2">
  				<tns:variable name="STDAL_SYM_CERTIFICATE_ALGORITHM" config="PROJECT" type="SymAuthMechEnum">
  					<tns:value>DES</tns:value>
  				</tns:variable>
  			</tns:dbLookupSpec>
  		</tns:dbLookupSpecs>
  		<tns:dbInterpolSpecs></tns:dbInterpolSpecs>
  	</tns:timingMapping></tns:timingMappings>
  <tns:dbLookups>
  	<tns:dbLookup id="1">
  		<tns:dbLookupDesc>This lookup ascertains the time needed to decrypt a 64 Bit element via AES</tns:dbLookupDesc>
  		<tns:dbLookupRequest>SELECT * FROM Measurements WHERE Type = 'DECRYPTION' AND Variant = 'MIC_1' AND Datasize=8 AND Algorithm = 'DES' AND Keysize = 128</tns:dbLookupRequest>
  	</tns:dbLookup>
  	  	<tns:dbLookup id="2">
  		<tns:dbLookupDesc>This lookup ascertains the time needed to encrypt a 64 Bit element via AES</tns:dbLookupDesc>
  		<tns:dbLookupRequest>SELECT * FROM Measurements WHERE Type = 'DECRYPTION' AND Variant = 'MIC_1' AND Datasize=8 AND Algorithm = 'AES' AND Keysize = 128</tns:dbLookupRequest>
  	</tns:dbLookup>
  </tns:dbLookups>
</tns:timing>
